# Generated by Django 5.1.4 on 2024-12-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_hotelimages_images_hotelimages_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimages',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
